[package]
name = "ai_project_template_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "process", "io-util", "time"] }
regex = "1"
anyhow = "1"
rfd = "0.14"
